In [1]:
import pandas as pd

# Load the dataset
# Replace 'your_dataset.csv' with the path to your dataset
file_path = '../dataset/prepared_dataset.csv'
data = pd.read_csv(file_path)
data.head()

,subject,label,HR_mean,HR_median,HR_min,HR_max,HR_max_amp,HR_range,HR_var,HR_std_dev,...,Wavelet_4Hz_RESPR_min,Wavelet_4Hz_RESPR_max,Wavelet_4Hz_RESPR_max_amp,Wavelet_4Hz_RESPR_range,Wavelet_4Hz_RESPR_var,Wavelet_4Hz_RESPR_std_dev,Wavelet_4Hz_RESPR_abs_dev,Wavelet_4Hz_RESPR_rms,Wavelet_4Hz_RESPR_kurtosis,Wavelet_4Hz_RESPR_skew
0,2,0,73.940333,70.68,69.07,118.00,44.059667,48.93,87.318183,9.344420,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342
1,2,0,73.184000,70.68,69.07,113.50,40.316000,44.43,53.863380,7.339168,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342
2,2,0,72.492000,70.68,69.07,93.25,20.758000,24.18,25.852159,5.084502,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342
3,2,0,72.147000,70.68,69.07,93.25,21.103000,24.18,18.603299,4.313154,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342
4,2,0,71.790667,70.68,69.07,86.40,14.609333,17.33,10.927396,3.305661,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342

In [2]:
data = data.fillna(0)
data.head()

,subject,label,HR_mean,HR_median,HR_min,HR_max,HR_max_amp,HR_range,HR_var,HR_std_dev,...,Wavelet_4Hz_RESPR_min,Wavelet_4Hz_RESPR_max,Wavelet_4Hz_RESPR_max_amp,Wavelet_4Hz_RESPR_range,Wavelet_4Hz_RESPR_var,Wavelet_4Hz_RESPR_std_dev,Wavelet_4Hz_RESPR_abs_dev,Wavelet_4Hz_RESPR_rms,Wavelet_4Hz_RESPR_kurtosis,Wavelet_4Hz_RESPR_skew
0,2,0,73.940333,70.68,69.07,118.00,44.059667,48.93,87.318183,9.344420,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342
1,2,0,73.184000,70.68,69.07,113.50,40.316000,44.43,53.863380,7.339168,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342
2,2,0,72.492000,70.68,69.07,93.25,20.758000,24.18,25.852159,5.084502,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342
3,2,0,72.147000,70.68,69.07,93.25,21.103000,24.18,18.603299,4.313154,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342
4,2,0,71.790667,70.68,69.07,86.40,14.609333,17.33,10.927396,3.305661,...,-3.691711e-16,-3.691711e-16,9.860761e-32,0.0,1.005875e-62,1.002933e-31,0.0,3.691711e-16,-2.148148,1.05342

In [56]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.combine import SMOTEENN

X = data.drop(columns=['label', 'subject'])
y = data['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True, stratify=y)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Resample the data
resampler = SMOTEENN(random_state=42)
X_train, y_train = resampler.fit_resample(X=X_train, y=y_train)

KeyboardInterrupt:

In [55]:
X_train.shape

(107752, 144)

In [44]:
import keras

# Define the model
model = keras.Sequential()
model.add(keras.layers.Input(shape=(144,)))
model.add(keras.layers.Dense(512, activation="relu"))
model.add(keras.layers.Dense(256, activation="relu"))
model.add(keras.layers.Dense(128, activation="relu"))
model.add(keras.layers.Dense(64, activation="relu"))
model.add(keras.layers.Dense(32, activation="relu"))
# Output layer with 1 neuron, sigmoid activation for binary classification
model.add(keras.layers.Dense(1, activation="sigmoid"))

optimizer = keras.optimizers.Adam(learning_rate=0.001)

model.compile(loss="binary_crossentropy", optimizer=optimizer, metrics=["accuracy"])

model.fit(X_train, y_train, validation_split=0.2, epochs=100, batch_size=32, verbose=1, callbacks=[keras.callbacks.EarlyStopping(patience=10, monitor='val_loss')])

Epoch 1/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.6943 - loss: 0.5519 - val_accuracy: 0.8179 - val_loss: 0.3891
Epoch 2/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.8846 - loss: 0.2654 - val_accuracy: 0.9384 - val_loss: 0.1654
Epoch 3/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9570 - loss: 0.1161 - val_accuracy: 0.9683 - val_loss: 0.0827
Epoch 4/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9726 - loss: 0.0747 - val_accuracy: 0.9762 - val_loss: 0.0663
Epoch 5/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9811 - loss: 0.0540 - val_accuracy: 0.9768 - val_loss: 0.0651
Epoch 6/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9846 - loss: 0.0442 - val_accuracy: 0.9931 - val_loss: 0.0227
Epoch 7/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9889 - loss: 0.0328 - val_accuracy: 0.9870 - val_loss: 0.0334
Epoch 8/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9893 - loss: 0.0317 - val_accuracy: 0.9930 - val_loss: 0.0225
Epoch 9/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9915 - loss: 0.0259 - val_accuracy: 0.9835 - val_loss: 0.0469
Epoch 10/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9921 - loss: 0.0267 - val_accuracy: 0.9925 - val_loss: 0.0205
Epoch 11/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9917 - loss: 0.0257 - val_accuracy: 0.9937 - val_loss: 0.0225
Epoch 12/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9937 - loss: 0.0213 - val_accuracy: 0.9807 - val_loss: 0.0544
Epoch 13/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9941 - loss: 0.0183 - val_accuracy: 0.9959 - val_loss: 0.0139
Epoch 14/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9949 - loss: 0.0165 - val_accuracy: 0.9929 - val_loss: 0.0224
Epoch 15/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9957 - loss: 0.0155 - val_accuracy: 0.9936 - val_loss: 0.0177
Epoch 16/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9953 - loss: 0.0159 - val_accuracy: 0.9891 - val_loss: 0.0425
Epoch 17/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9957 - loss: 0.0151 - val_accuracy: 0.9955 - val_loss: 0.0229
Epoch 18/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9953 - loss: 0.0160 - val_accuracy: 0.9916 - val_loss: 0.0257
Epoch 19/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9962 - loss: 0.0145 - val_accuracy: 0.9969 - val_loss: 0.0094
Epoch 20/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9963 - loss: 0.0122 - val_accuracy: 0.9948 - val_loss: 0.0167
Epoch 21/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9974 - loss: 0.0095 - val_accuracy: 0.9965 - val_loss: 0.0099
Epoch 22/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9972 - loss: 0.0099 - val_accuracy: 0.9903 - val_loss: 0.0336
Epoch 23/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9972 - loss: 0.0100 - val_accuracy: 0.9980 - val_loss: 0.0080
Epoch 24/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9968 - loss: 0.0108 - val_accuracy: 0.9985 - val_loss: 0.0044
Epoch 25/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9976 - loss: 0.0093 - val_accuracy: 0.9990 - val_loss: 0.0044
Epoch 26/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9977 - loss: 0.0080 - val_accuracy: 0.9970 - val_loss: 0.0074
Epoch 27/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9978 - loss: 0.0066 - val_accuracy: 0.9994 - val_loss: 0.0020
Epoch 28/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9976 - loss: 0.0114 - val_accuracy: 0.9995 - val_loss: 0.0021
Epoch 29/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9980 - loss: 0.0068 - val_accuracy: 0.9996 - val_loss: 0.0012
Epoch 30/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9972 - loss: 0.0086 - val_accuracy: 0.9991 - val_loss: 0.0039
Epoch 31/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9978 - loss: 0.0096 - val_accuracy: 0.9992 - val_loss: 0.0038
Epoch 32/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9976 - loss: 0.0089 - val_accuracy: 0.9984 - val_loss: 0.0038
Epoch 33/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9986 - loss: 0.0047 - val_accuracy: 0.9991 - val_loss: 0.0038
Epoch 34/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9979 - loss: 0.0085 - val_accuracy: 0.9956 - val_loss: 0.0159
Epoch 35/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9981 - loss: 0.0071 - val_accuracy: 0.9993 - val_loss: 0.0032
Epoch 36/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9971 - loss: 0.0132 - val_accuracy: 0.9996 - val_loss: 0.0015
Epoch 37/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9984 - loss: 0.0058 - val_accuracy: 0.9955 - val_loss: 0.0240
Epoch 38/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9976 - loss: 0.0090 - val_accuracy: 0.9991 - val_loss: 0.0029
Epoch 39/100
2694/2694 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9984 - loss: 0.0071 - val_accuracy: 0.9991 - val_loss: 0.0048

In [41]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=10000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [45]:
model.predict(X_test)

616/616 ━━━━━━━━━━━━━━━━━━━━ 0s 619us/step

array([[4.4477322e-10],
       [3.1976113e-05],
       [4.1937720e-09],
       ...,
       [5.5203998e-30],
       [1.0000000e+00],
       [1.0000000e+00]], dtype=float32)

In [47]:
from sklearn.metrics import f1_score

f1_score(y_test, model.predict(X_test) > 0.5)

616/616 ━━━━━━━━━━━━━━━━━━━━ 0s 601us/step

0.9926070355024779