In [5]:
import pandas as pd

original_df = pd.read_csv("../../../datasets/nurse/raw/nurse_no_features.csv", low_memory=False)

In [6]:
original_df[original_df["EDA"] == 0].count()

X           31104
Y           31104
Z           31104
EDA         31104
HR          31104
TEMP        31104
id          31104
datetime    31104
label       31104
dtype: int64

In [7]:
original_df = original_df[original_df["EDA"] != 0]

In [8]:
new_df = original_df
# Ensure the datetime column is in datetime format
new_df["datetime"] = pd.to_datetime(new_df["datetime"])

# Get time of day and date of year as separate features. time of day in hours
new_df["time_of_day"] = new_df["datetime"].dt.hour + new_df["datetime"].dt.minute / 60
new_df["date_of_year"] = new_df["datetime"].dt.dayofyear
new_df = new_df.drop(columns=["datetime"])
# relabel 2 as 1
new_df["label"] = new_df["label"].replace(2, 1)
# rename id column to Participant
new_df = new_df.rename(columns={"id": "Participant"})
# rename label column to Label
new_df = new_df.rename(columns={"label": "Label"})
# Shuffle
new_df = new_df.sample(frac=1, random_state=42).reset_index(drop=True)
new_df.head()

,X,Y,Z,EDA,HR,TEMP,Participant,Label,time_of_day,date_of_year
0,-55.0,-18.0,26.0,1.979182,82.10,32.79,83,1.0,12.350000,345
1,-57.0,22.0,-1.0,0.143492,93.68,29.71,DF,1.0,20.800000,219
2,-58.0,-27.0,0.0,15.396890,74.25,34.43,E4,1.0,15.366667,181
3,-42.0,51.0,1.0,2.456436,79.97,29.81,6B,0.0,13.850000,181
4,10.0,52.0,36.0,0.521492,81.97,30.93,F5,1.0,17.466667,203

In [11]:
# Remove id "CE" and "EG"
# new_df = new_df[new_df["id"] != "CE"]
# new_df = new_df[new_df["id"] != "EG"]

In [9]:
new_df.dtypes

X               float64
Y               float64
Z               float64
EDA             float64
HR              float64
TEMP            float64
Participant      object
Label           float64
time_of_day     float64
date_of_year      int32
dtype: object

In [12]:
# convert float64 to float32
# for col in new_df.select_dtypes(include=["float64"]).columns:
#     new_df[col] = new_df[col].astype(np.float32)

# Save the dataset
new_df.to_pickle("../../../datasets/nurse/paper/all.pkl")

for participant in new_df["Participant"].unique():
    participant_data = new_df[new_df["Participant"] == participant]
    participant_data.to_pickle(f"../../../datasets/nurse/paper/{participant}.pkl")

In [15]:
from enums.Participant import NurseParticipant

test = pd.read_pickle(f"../../../datasets/nurse/paper/{NurseParticipant.n_DF}.pkl")
test.head()

,X,Y,Z,EDA,HR,TEMP,Participant,Label,time_of_day,date_of_year
8028182,-21.0,-20.0,55.0,0.096083,90.55,29.87,DF,1.0,14.016667,203
8028183,-20.0,-20.0,55.0,0.096083,90.55,29.87,DF,1.0,14.016667,203
8028184,-20.0,-20.0,55.0,0.096083,90.55,29.87,DF,1.0,14.016667,203
8028185,-20.0,-20.0,55.0,0.096083,90.55,29.87,DF,1.0,14.016667,203
8028186,-20.0,-20.0,55.0,0.096083,90.55,29.87,DF,1.0,14.016667,203